### ISSUE TITLE
List on Packagist

### ISSUE THREAD

**Issue by davidwindell** [kraken-io/kraken-magento#11]
Please can you list this extension on packagist so it can be installed with composer without needed to add the repository URL.

Thanks!

**Comment by ustuehler** [comment]
Hi!

It is [published](https://packagist.org/packages/kraken-io/kraken-php) on packagist and it shows up when I [search](https://packagist.org/?query=kraken-io) for "kraken-io".

Could you explain what you mean by "list this extension"? Do you mean listing it somewhere else?

**Comment by davidwindell** [comment]
Only kraken-php is on packagist, not kraken-magento

**Comment by ustuehler** [comment]
Sorry. My fault. We're fixing this in the coming days!
