### ISSUE TITLE
Nicer Image Names

### ISSUE THREAD

**Issue by elfeffe** [kraken-io/kraken-magento#2]
Hi there, your extension doesn't work with https://github.com/Vinai/nicer-image-names
It doesn't create the "Nice Image names", when I disable Kraken, Nicer Images works again.
Can you fix it?

**Comment by karim79** [comment]
Hi,

We are looking into this at the moment, to see what can be done.

Karim

**Comment by karim79** [comment]
Hi,

We have created forks of both the Kraken.io Magento extension as well as the nicer image names extension, that play nicely together:

https://github.com/mgal/kraken-magento
https://github.com/mgal/nicer-image-names

Could you install those forks and let us know how it goes? From there, we will figure out the way forward.

Also, could you touch base with me at Kraken.io support?

-Karim
