### ISSUE TITLE
Missing quota_used in userStatus response

### ISSUE THREAD

**Issue by fasimana** [kraken-io/kraken-magento#4]
Hello,

I got a notice when quota_used is missing from API response.
This is the original response

> {"success":true,"active":true,"plan_name":"Free","quota_total":52428800,"quota_remaining":null}

And notices

> Notice: Undefined property: stdClass::$quota_used  in .../app/code/local/Welance/Kraken/controllers/KrakenController.php on line 18
> Notice: Undefined property: stdClass::$quota_used  in .../app/design/adminhtml/default/default/template/kraken/statistics.phtml on line 25

**Comment by matylla** [comment]
Fixed in 2.0.5
